Repository ICOS-Carbon-Portal/jupyter, pull requests merged in 2022-11, with the labels that each got.

#246 Is network char ouput display update
  notebooks/icos_jupyter_notebooks/network_characterization/gui_network_characterization.py
  notebooks/icos_jupyter_notebooks/network_characterization/network_characterization_functions.py
Labels: enhancement, fix

#248 Is radiocarbon updates
  notebooks/icos_jupyter_notebooks/radiocarbon/gui_overview_radiocarbon.py
  notebooks/icos_jupyter_notebooks/radiocarbon/gui_stilt.py
  notebooks/icos_jupyter_notebooks/radiocarbon/radiocarbon_functions.py
Labels: enhancement

#249 updated instructions for how to run a notebook cell
  notebooks/icos_jupyter_notebooks/network_characterization/screenshots_for_into_texts/how_to_run.PNG
  notebooks/icos_jupyter_notebooks/station_characterization.ipynb
Labels: documentation, enhancement

#253 small updates network characterization
  docker/icosbase/Dockerfile
  docs/changelog.md
  notebooks/icos_jupyter_notebooks/network_characterization/gui_network_characterization.py
  notebooks/icos_jupyter_notebooks/network_characterization/network_characterization_functions.py
Labels: documentation, enhancement, fix

#252 Update ccgcrv
  notebooks/icos_jupyter_notebooks/ccg/ccg_icos_tools.ipynb
  notebooks/icos_jupyter_notebooks/ccgcrv.ipynb
Labels: bug, enhancement
