Repository ICOS-Carbon-Portal/jupyter, pull requests merged in 2022-09, with the labels that each got.

#225 zz remove icos atmobs stilt notebook
  docker/icosbase/Dockerfile
  notebooks/icos_jupyter_notebooks/icos_atmObs_STILT.ipynb
  notebooks/icos_jupyter_notebooks/ind_tools/json/nb_info.json
  notebooks/icos_jupyter_notebooks/ind_tools/tools.ipynb
Labels: fix

#228 zz filter incomplete uploads
  notebooks/icos_jupyter_notebooks/availability_tools/icos_availability_tools.ipynb
Labels: fix

#231 zz error when importing xarray
  docker/icosbase/Dockerfile
Labels: bug

#234 233 install latest pylib
  docker/icosbase/Dockerfile
Labels: enhancement, pylib

#235 seasonal table + multiple variables graph for new STILT stations
  notebooks/icos_jupyter_notebooks/station_characterization/stc_functions.py
Labels: fix
