Repository ICOS-Carbon-Portal/jupyter, pull requests merged in 2023-03, with the labels that each got.

#269 Fixed columns for the STILT availability table
  notebooks/pylib_examples/ex6a_STILT_find.ipynb
Labels: fix

#267 Improve explanation to find `sparql query`
  notebooks/pylib_examples/ex5_sparql.ipynb
  notebooks/pylib_examples/img/sparql.png
Labels: improvement

#265 Removed `ShapelyDeprecationWarning`
  notebooks/pylib_examples/ex3_multisource.ipynb
Labels: improvement

#272 262 update docker image to version 2.1.0
  docker/icosbase/Dockerfile
  docker/icosbase/pip_requirements.txt
  docs/changelog.md
  templates/exploredata/login.html
  templates/jupyter/login.html
Labels: docker image, [minor]

#275 274 fix announcement ribbon
  notebooks/radon_tracer_method_for_ghg/README.md
  radon_tracer_method_for_ghg/README.md
  templates/exploredata/login.html
  templates/jupyter/login.html
Labels: documentation, improvement

#281 280 remove workshop data
  notebooks/project_jupyter_notebooks/radon_tracer_method_for_ghg/README.md
Labels: enhancement

#278 279 add zip command to the system
  docker/icosbase/Dockerfile
Labels: enhancement

#283 282 update changelog
  docs/changelog.md
Labels: documentation, enhancement
