Repository ICOS-Carbon-Portal/jupyter, pull requests merged in 2023-05, with the labels that each got.

#308 306 fix notebook output directory
  notebooks/icos_jupyter_notebooks/ecosystem_site_anomaly_visualization.ipynb
  notebooks/icos_jupyter_notebooks/ecosystem_site_anomaly_visualization/gui_anomaly.py
  notebooks/icos_jupyter_notebooks/ecosystem_site_anomaly_visualization/plot_interface_anomaly.py
  notebooks/icos_jupyter_notebooks/station_characterization/gui.py
  notebooks/project_jupyter_notebooks/network-view-tool/network_view.ipynb
  notebooks/project_jupyter_notebooks/network-view-tool/network_view/create_network_analysis.py
  notebooks/project_jupyter_notebooks/network-view-tool/network_view/gui_network.py
  notebooks/project_jupyter_notebooks/network-view-tool/network_view/gui_station.py
  notebooks/project_jupyter_notebooks/network-view-tool/network_view/network_analysis_functions.py
Labels: bug

#307 visualize average footprint update
  notebooks/icos_jupyter_notebooks/network_characterization/gui_percent_aggregate_footprints.py
  notebooks/icos_jupyter_notebooks/network_characterization/visualization_average_footprints.ipynb
  notebooks/icos_jupyter_notebooks/visualization_average_footprints.ipynb
Labels: bug

#309 Minor updates (into + name of output)
  notebooks/icos_jupyter_notebooks/ecosystem_site_anomaly_visualization.ipynb
  notebooks/icos_jupyter_notebooks/ecosystem_site_anomaly_visualization/plot_interface_anomaly.py
Labels: bug

#311 310 edit login templates
  templates/exploredata/login.html
  templates/jupyter/login.html
Labels: feature

#313 312 update mamba requirements
  docker/icosbase/mamba_requirements.txt
  docs/changelog.md
Labels: documentation, feature

#316 314 remove maintenance announcement
  templates/exploredata/login.html
  templates/jupyter/login.html
Labels: feature
