Repository ICOS-Carbon-Portal/jupyter, pull requests merged in 2023-04, with the labels that each got.

#287 Is network view updates
  notebooks/project_jupyter_notebooks/network-view-tool/network_view.ipynb
  notebooks/project_jupyter_notebooks/network-view-tool/network_view/create_network_analysis.ipynb
  notebooks/project_jupyter_notebooks/network-view-tool/network_view/create_network_analysis.py
  notebooks/project_jupyter_notebooks/network-view-tool/network_view/gui_create_network_view.py
  notebooks/project_jupyter_notebooks/network-view-tool/network_view/gui_create_network_view_from_extension.py
  notebooks/project_jupyter_notebooks/network-view-tool/network_view/gui_network.py
  notebooks/project_jupyter_notebooks/network-view-tool/network_view/gui_station.py
  notebooks/project_jupyter_notebooks/network-view-tool/network_view/network_analysis_functions.py
  notebooks/project_jupyter_notebooks/network-view-tool/network_view/station_map.py
Labels: feature

#285 current year and local solar time
  notebooks/project_jupyter_notebooks/RINGO_T1.3/ICOS_flasksampling_fossilfuel.ipynb
  notebooks/project_jupyter_notebooks/RINGO_T1.3/RINGO_T1.3_flasksampling_v5.ipynb
  notebooks/project_jupyter_notebooks/RINGO_T1.3/modules/STILT_modules_plus.py
  notebooks/project_jupyter_notebooks/RINGO_T1.3/modules/flasksampling_modules.ipynb
  notebooks/project_jupyter_notebooks/RINGO_T1.3/modules/flasksampling_modules_ff.ipynb
Labels: improvement

#291 updates tested - revert changes to upload settings
  notebooks/icos_jupyter_notebooks/network_characterization/gui_network_characterization.py
  notebooks/icos_jupyter_notebooks/radiocarbon/gui_stilt.py
  notebooks/icos_jupyter_notebooks/station_characterization/gui.py
Labels: bug

#292 286 add terms checkbox
  templates/exploredata/login.html
  templates/jupyter/login.html
Labels: feature

#289 Update STILT_modules_plus.py
  notebooks/project_jupyter_notebooks/RINGO_T1.3/modules/STILT_modules_plus.py
Labels: bug

#294 293 specify ipywidgets version
  docker/icosbase/mamba_requirements.txt
  docs/changelog.md
Labels: improvement

#295 Revert "286 add terms checkbox"
  templates/exploredata/login.html
  templates/jupyter/login.html
Labels: bug

#296 286 add terms checkbox
  templates/exploredata/login.html
  templates/jupyter/login.html
Labels: bug

#297 Revert "286 add terms checkbox"
  templates/exploredata/login.html
  templates/jupyter/login.html
Labels: bug

#298 286 add terms checkbox
  templates/exploredata/login.html
  templates/jupyter/login.html
Labels: bug

#299 ringo notebooks update year and mst
  notebooks/project_jupyter_notebooks/RINGO_T1.3/modules/flasksampling_modules.ipynb
  notebooks/project_jupyter_notebooks/RINGO_T1.3/modules/flasksampling_modules_ff.ipynb
Labels: feature

#304 303 update pip requirements
  docker/icosbase/pip_requirements.txt
  docs/changelog.md
Labels: documentation, feature

#305 Is flux anomaly launch
  notebooks/icos_jupyter_notebooks/ecosystem_site_anomaly_visualization.ipynb
  notebooks/icos_jupyter_notebooks/ecosystem_site_anomaly_visualization/gui_anomaly.py
  notebooks/icos_jupyter_notebooks/ecosystem_site_anomaly_visualization/img/Mean_daily_GPP_DT_VUT_REF_for_July_at_Hainich_2018_wrt_2000-2020.png
  notebooks/icos_jupyter_notebooks/ecosystem_site_anomaly_visualization/img/Mean_monthly_GPP_DT_VUT_REF_at_Hainich_2018__left_top__GPP_DT_VUT_REF_at_Hyytiala_2018__right_bottom_wrt_2000-2020.png
  notebooks/icos_jupyter_notebooks/ecosystem_site_anomaly_visualization/img/gi-Logo.png
  notebooks/icos_jupyter_notebooks/ecosystem_site_anomaly_visualization/img/how_to_run_flux.png
  notebooks/icos_jupyter_notebooks/ecosystem_site_anomaly_visualization/img/visual_explanation_bars.png
  notebooks/icos_jupyter_notebooks/ecosystem_site_anomaly_visualization/img/visual_explanation_piechart.png
  notebooks/icos_jupyter_notebooks/ecosystem_site_anomaly_visualization/plot_interface_anomaly.py
Labels: feature
