Repository ICOS-Carbon-Portal/jupyter, pull requests merged in 2024-04, with the labels that each got.

#366 Update ex6c_STILT_timeseries.ipynb
  notebooks/pylib_examples/ex6c_STILT_timeseries.ipynb
Labels: feature

#368 367 install latest pylib master
  docker/icosbase/Dockerfile
  notebooks/pylib_examples/ex1_data.ipynb
  notebooks/pylib_examples/ex5_sparql.ipynb
Labels: feature

#370 369 fix docs
  docs/changelog.md
Labels: documentation, fix, feature

#371 Update to axis + added example
  notebooks/pylib_examples/ex6c_STILT_timeseries.ipynb
Labels: fix
